# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - fuem

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Prepare appsettings.Production.json
        shell: pwsh
        run: |
          $json = Get-Content 'FUEM.Web/appsettings.Production.json' | ConvertFrom-Json
          $json.ConnectionStrings.Server = "${{ secrets.DB_SERVER }}"
          $json.ConnectionStrings.UserId = "${{ secrets.DB_USER }}"
          $json.ConnectionStrings.Password = "${{ secrets.DB_PASSWORD }}"
          $json.ConnectionStrings.Database = "${{ secrets.DB_NAME }}"
          $json.MongoDb.ConnectionString = "${{ secrets.MONGO_CONNECTION_STRING }}"
          $json.MongoDb.DatabaseName = "${{ secrets.MONGO_DB_NAME }}"
          $json.PayOS.ClientId = "${{ secrets.PAYOS_CLIENT_ID }}"
          $json.PayOS.ApiKey = "${{ secrets.PAYOS_API_KEY }}"
          $json.PayOS.ChecksumKey = "${{ secrets.PAYOS_CHECKSUM_KEY }}"
          $json.Authentication.Google.ClientId = "${{ secrets.GG_CLIENT_ID }}"
          $json.Authentication.Google.ClientSecret = "${{ secrets.GG_CLIENT_SECRET }}"
          $json.Mail.Sender = "${{ secrets.GG_CLIENT_SECRET }}"
          $json.Mail.SenderAppPassword = "${{ secrets.MAIL_SENDER_APP_PASSWORD }}"
          $json | ConvertTo-Json -Depth 10 | Set-Content 'FUEM.Web/appsettings.Production.json'

      - name: Write Firebase Admin SDK JSON to file
        shell: pwsh
        run: |
          $firebaseJson = "${{ secrets.FIREBASE_ADMIN_KEY_JSON }}"
          Set-Content -Path "FUEM.Infrastructure/fu-event-management-firebase-service-account.Production.json" -Value $firebaseJson

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7E3C44D976BE4728BC3A6D0B5175328A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_A4D952B564C14252B4F381BFC577D955 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6E3FF0857B354B7DBB085744CD097A50 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'fuem'
          slot-name: 'Production'
          package: .
          
