name: Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
      issues: write

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\.sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
      - name: Build and analyze
        shell: powershell
        env:
          # Đảm bảo SONAR_TOKEN được truyền qua biến môi trường để an toàn
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"hoanghung256_fu-event-management" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:sonar.pullrequest.key="${{ github.event.pull_request.number }}" `
            /d:sonar.pullrequest.branch="${{ github.head_ref }}" `
            /d:sonar.pullrequest.base="${{ github.base_ref }}" `
            /d:sonar.pullrequest.provider="GitHub" `
            /d:sonar.pullrequest.github.repository="${{ github.repository }}"
          dotnet build
          .\.sonar\scanner\dotnet-sonarscanner end